USE PROTOLENGUAJE
DELETE FROM ReglasSemanticas
/*Estados Finales*/
INSERT INTO ReglasSemanticas VALUES('INTD','S')
INSERT INTO ReglasSemanticas VALUES('DBLD','S')
INSERT INTO ReglasSemanticas VALUES('STRD','S')
INSERT INTO ReglasSemanticas VALUES('CHRD','S')
INSERT INTO ReglasSemanticas VALUES('BOLD','S')
INSERT INTO ReglasSemanticas VALUES('ASGE','S')
INSERT INTO ReglasSemanticas VALUES('IFTK','S')
INSERT INTO ReglasSemanticas VALUES('PR05','S')
INSERT INTO ReglasSemanticas VALUES('PR20 PAR1 BOOL PAR2','S');
INSERT INTO ReglasSemanticas VALUES('PR08 PAR1 BOOL PAR2','S')
INSERT INTO ReglasSemanticas VALUES('BOLD OPA6 PR23','S')
INSERT INTO ReglasSemanticas VALUES('BOLD OPA6 PR22','S')
INSERT INTO ReglasSemanticas VALUES('PR21','S')
/*Operaciones relacionales*/
INSERT INTO ReglasSemanticas VALUES('OPR1','OPRE')
INSERT INTO ReglasSemanticas VALUES('OPR2','OPRE')
INSERT INTO ReglasSemanticas VALUES('OPR3','OPRE')
INSERT INTO ReglasSemanticas VALUES('OPR4','OPRE')
INSERT INTO ReglasSemanticas VALUES('OPR5','OPRE')
INSERT INTO ReglasSemanticas VALUES('OPR6','OPRE')
INSERT INTO ReglasSemanticas VALUES('INTE OPRE INTE','BOOL')
INSERT INTO ReglasSemanticas VALUES('INTE OPRE DBLE','BOOL')
INSERT INTO ReglasSemanticas VALUES('DBLE OPRE DBLE','BOOL')
INSERT INTO ReglasSemanticas VALUES('DBLE OPRE INTE','BOOL')
INSERT INTO ReglasSemanticas VALUES('CHAR OPRE CHAR','BOOL')
INSERT INTO ReglasSemanticas VALUES('STRG OPRE STRG','BOOL')
/*Asignaciones*/
INSERT INTO ReglasSemanticas VALUES('TDD1 INTE','INTD')
INSERT INTO ReglasSemanticas VALUES('TDD2 DBLE','DBLD')
INSERT INTO ReglasSemanticas VALUES('TDD3 STRG','STRD')
INSERT INTO ReglasSemanticas VALUES('TDD4 CHAR','CHRD')
INSERT INTO ReglasSemanticas VALUES('TDD5 BOOL','BOLD')
INSERT INTO ReglasSemanticas VALUES('INTD OPA6 INTE','ASGE')
/*Operaciones Aritmeticas*/
INSERT INTO ReglasSemanticas VALUES('OPA1','OPAR')
INSERT INTO ReglasSemanticas VALUES('OPA2','OPAR')
INSERT INTO ReglasSemanticas VALUES('OPA3','OPAR')
INSERT INTO ReglasSemanticas VALUES('OPA4','OPAR')
INSERT INTO ReglasSemanticas VALUES('OPA5','OPAR')
INSERT INTO ReglasSemanticas VALUES('INTE OPAR INTE','INTE')
INSERT INTO ReglasSemanticas VALUES('INTE OPA2 INTE','DBLE')
INSERT INTO ReglasSemanticas VALUES('DBLE OPA2 INTE','DBLE')
INSERT INTO ReglasSemanticas VALUES('DBLE OPA2 DBLE','DBLE')
INSERT INTO ReglasSemanticas VALUES('INTE OPA2 DBLE','DBLE')
INSERT INTO ReglasSemanticas VALUES('DBLE OPAR DBLE','DBLE')
INSERT INTO ReglasSemanticas VALUES('DBLE OPAR INTE','DBLE')
INSERT INTO ReglasSemanticas VALUES('INTE OPAR DBLE','DBLE')

/*Operaciones logicas*/
INSERT INTO ReglasSemanticas VALUES('OL03 BOOL','BOOL')
INSERT INTO ReglasSemanticas VALUES('BOOL OL01 BOOL','BOOL')
INSERT INTO ReglasSemanticas VALUES('BOOL OL02 BOOL','BOOL')

SELECT * FROM ReglasSemanticas
