USE PROTOLENGUAJE
DELETE FROM ReglasSemanticas
INSERT INTO ReglasSemanticas VALUES('INTD','S')
INSERT INTO ReglasSemanticas VALUES('DBLD','S')
INSERT INTO ReglasSemanticas VALUES('STRD','S')
INSERT INTO ReglasSemanticas VALUES('CHRD','S')
INSERT INTO ReglasSemanticas VALUES('BOLD','S')
INSERT INTO ReglasSemanticas VALUES('ASGE','S')
INSERT INTO ReglasSemanticas VALUES('TDD1 INTE','INTD')
INSERT INTO ReglasSemanticas VALUES('TDD2 DBLE','DBLD')
INSERT INTO ReglasSemanticas VALUES('TDD3 STRG','STRD')
INSERT INTO ReglasSemanticas VALUES('TDD4 CHAR','CHRD')
INSERT INTO ReglasSemanticas VALUES('TDD5 BOOL','BOLD')
INSERT INTO ReglasSemanticas VALUES('BOLD OPA6 PR23','S')
INSERT INTO ReglasSemanticas VALUES('BOLD OPA6 PR22','S')
INSERT INTO ReglasSemanticas VALUES('INTD OPA6 INTE','ASGE')
INSERT INTO ReglasSemanticas VALUES('INTE OPA1 INTE','INTE')
INSERT INTO ReglasSemanticas VALUES('INTE OPA2 INTE','DBLE')
INSERT INTO ReglasSemanticas VALUES('INTE OPA4 INTE','INTE')
INSERT INTO ReglasSemanticas VALUES('INTE OPA5 INTE','INTE')
INSERT INTO ReglasSemanticas VALUES('INTE OPA2 DBLE','DBLE')
INSERT INTO ReglasSemanticas VALUES('INTE OPA4 DBLE','DBLE')




SELECT * FROM ReglasSemanticas
