USE PROTOLENGUAJE
DELETE FROM ReglasSemanticas
/*Estados Finales*/
INSERT INTO ReglasSemanticas VALUES('INTD','S')
INSERT INTO ReglasSemanticas VALUES('DBLD','S')
INSERT INTO ReglasSemanticas VALUES('CADE','STRG')
INSERT INTO ReglasSemanticas VALUES('STRD','S')
INSERT INTO ReglasSemanticas VALUES('CHRD','S')
INSERT INTO ReglasSemanticas VALUES('BOLD','S')
INSERT INTO ReglasSemanticas VALUES('ASGC','S')
INSERT INTO ReglasSemanticas VALUES('ASGE','S')
INSERT INTO ReglasSemanticas VALUES('ASGD','S')
INSERT INTO ReglasSemanticas VALUES('ASGB','S')
INSERT INTO ReglasSemanticas VALUES('ASST','S')
INSERT INTO ReglasSemanticas VALUES('ASCH','S')
INSERT INTO ReglasSemanticas VALUES('IFTK','S')
INSERT INTO ReglasSemanticas VALUES('PR05','S')
INSERT INTO ReglasSemanticas VALUES('FINT','S')
INSERT INTO ReglasSemanticas VALUES('FDEN','S')
INSERT INTO ReglasSemanticas VALUES('PR20 PAR1 BOOL PAR2','S');
INSERT INTO ReglasSemanticas VALUES('PR08 PAR1 BOOL PAR2','S')
INSERT INTO ReglasSemanticas VALUES('BOLD OPA6 PR23','S')
INSERT INTO ReglasSemanticas VALUES('BOLD OPA6 PR22','S')
INSERT INTO ReglasSemanticas VALUES('PR21','S')
INSERT INTO ReglasSemanticas VALUES('PR06 PAR1 ASGE PR19 BOOL PR17 ASGE PAR2','S')
/*Operaciones relacionales*/
INSERT INTO ReglasSemanticas VALUES('OPR1','OPRE')
INSERT INTO ReglasSemanticas VALUES('OPR2','OPRE')
INSERT INTO ReglasSemanticas VALUES('OPR3','OPRE')
INSERT INTO ReglasSemanticas VALUES('OPR4','OPRE')
INSERT INTO ReglasSemanticas VALUES('OPR5','OPRE')
INSERT INTO ReglasSemanticas VALUES('OPR6','OPRE')
INSERT INTO ReglasSemanticas VALUES('INTE OPRE INTE','BOOL')
INSERT INTO ReglasSemanticas VALUES('INTE OPRE DBLE','BOOL')
INSERT INTO ReglasSemanticas VALUES('DBLE OPRE DBLE','BOOL')
INSERT INTO ReglasSemanticas VALUES('DBLE OPRE INTE','BOOL')
INSERT INTO ReglasSemanticas VALUES('CHAR OPRE CHAR','BOOL')
INSERT INTO ReglasSemanticas VALUES('STRG OPRE STRG','BOOL')
/*Asignaciones*/
INSERT INTO ReglasSemanticas VALUES('TDD1 INTE','INTD')
INSERT INTO ReglasSemanticas VALUES('TDD2 DBLE','DBLD')
INSERT INTO ReglasSemanticas VALUES('TDD3 STRG','STRD')
INSERT INTO ReglasSemanticas VALUES('TDD4 CHAR','CHRD')
INSERT INTO ReglasSemanticas VALUES('TDD5 BOOL','BOLD')

INSERT INTO ReglasSemanticas VALUES('INTE OPA6','ASGE')
INSERT INTO ReglasSemanticas VALUES('DBLE OPA6','ASGD')
INSERT INTO ReglasSemanticas VALUES('CHAR OPA6','ASCH')
INSERT INTO ReglasSemanticas VALUES('STRG OPA6','ASST')
INSERT INTO ReglasSemanticas VALUES('BOOL OPA6','ASGB')

INSERT INTO ReglasSemanticas VALUES('ASGE INTE','ASGE')
INSERT INTO ReglasSemanticas VALUES('ASGD DBLE','ASGD')
INSERT INTO ReglasSemanticas VALUES('ASCH CHAR','ASCH')
INSERT INTO ReglasSemanticas VALUES('ASST STRG','ASST')
INSERT INTO ReglasSemanticas VALUES('ASGB BOOL','ASGB')

INSERT INTO ReglasSemanticas VALUES('INTD OPA6','ASGE')
INSERT INTO ReglasSemanticas VALUES('DBLD OPA6','ASGD')
INSERT INTO ReglasSemanticas VALUES('STRD OPA6','ASST')
INSERT INTO ReglasSemanticas VALUES('BOLD OPA6','ASGB')
INSERT INTO ReglasSemanticas VALUES('CHRD OPA6','ASCH')
/*Operaciones Aritmeticas*/

INSERT INTO ReglasSemanticas VALUES('INTE OPA1 INTE','INTE')
INSERT INTO ReglasSemanticas VALUES('INTE OPA3 INTE','INTE')
INSERT INTO ReglasSemanticas VALUES('INTE OPA4 INTE','INTE')
INSERT INTO ReglasSemanticas VALUES('INTE OPA5 INTE','INTE')
INSERT INTO ReglasSemanticas VALUES('INTE OPA2 INTE','DBLE')
INSERT INTO ReglasSemanticas VALUES('DBLE OPA2 INTE','DBLE')
INSERT INTO ReglasSemanticas VALUES('DBLE OPA2 DBLE','DBLE')
INSERT INTO ReglasSemanticas VALUES('INTE OPA2 DBLE','DBLE')
INSERT INTO ReglasSemanticas VALUES('DBLE OPA1 DBLE','DBLE')
INSERT INTO ReglasSemanticas VALUES('DBLE OPA3 DBLE','DBLE')
INSERT INTO ReglasSemanticas VALUES('DBLE OPA4 DBLE','DBLE')
INSERT INTO ReglasSemanticas VALUES('DBLE OPA5 DBLE','DBLE')
INSERT INTO ReglasSemanticas VALUES('DBLE OPA1 INTE','DBLE')
INSERT INTO ReglasSemanticas VALUES('DBLE OPA3 INTE','DBLE')
INSERT INTO ReglasSemanticas VALUES('DBLE OPA4 INTE','DBLE')
INSERT INTO ReglasSemanticas VALUES('DBLE OPA5 INTE','DBLE')
INSERT INTO ReglasSemanticas VALUES('INTE OPA1 DBLE','DBLE')
INSERT INTO ReglasSemanticas VALUES('INTE OPA3 DBLE','DBLE')
INSERT INTO ReglasSemanticas VALUES('INTE OPA4 DBLE','DBLE')
INSERT INTO ReglasSemanticas VALUES('INTE OPA5 DBLE','DBLE')

/*Operaciones logicas*/
INSERT INTO ReglasSemanticas VALUES('OL03 BOOL','BOOL')
INSERT INTO ReglasSemanticas VALUES('BOOL OL01 BOOL','BOOL')
INSERT INTO ReglasSemanticas VALUES('BOOL OL02 BOOL','BOOL')
/*print*/
INSERT INTO ReglasSemanticas VALUES('PR09 PAR1 INTE PAR2','S')
INSERT INTO ReglasSemanticas VALUES('PR09 PAR1 STRG PAR2','S')
INSERT INTO ReglasSemanticas VALUES('PR09 PAR1 CHAR PAR2','S')
INSERT INTO ReglasSemanticas VALUES('PR09 PAR1 DBLE PAR2','S')

/*read*/
INSERT INTO ReglasSemanticas VALUES('PR13 INTE','S')
INSERT INTO ReglasSemanticas VALUES('PR13 STRG','S')
INSERT INTO ReglasSemanticas VALUES('PR13 CHAR','S')
INSERT INTO ReglasSemanticas VALUES('PR13 DBLE','S')

/*Funciones*/
INSERT INTO ReglasSemanticas VALUES('FIEN PAR2','FINT')
INSERT INTO ReglasSemanticas VALUES('ASGE INTE PAR1','FIEN')
INSERT INTO ReglasSemanticas VALUES('ASGD DBLE PAR1','FIEN')
INSERT INTO ReglasSemanticas VALUES('ASCH CHAR PAR1','FIEN')
INSERT INTO ReglasSemanticas VALUES('ASST STRG PAR1','FIEN')
INSERT INTO ReglasSemanticas VALUES('ASGB BOOL PAR1','FIEN')
INSERT INTO ReglasSemanticas VALUES('FIEN INTE','FIEN')
INSERT INTO ReglasSemanticas VALUES('FIEN STRG','FIEN')
INSERT INTO ReglasSemanticas VALUES('FIEN CHAR','FIEN')
INSERT INTO ReglasSemanticas VALUES('FIEN DBLE','FIEN')
INSERT INTO ReglasSemanticas VALUES('FIEN BOOL','FIEN')

INSERT INTO ReglasSemanticas VALUES('FDEN PRMT PAR2','FDEN')
INSERT INTO ReglasSemanticas VALUES('PR07 INTD','FDEN')
INSERT INTO ReglasSemanticas VALUES('PR07 DBLD','FDEN')
INSERT INTO ReglasSemanticas VALUES('PR07 BOLD','FDEN')
INSERT INTO ReglasSemanticas VALUES('PR07 STRD','FDEN')
INSERT INTO ReglasSemanticas VALUES('PR07 CHRD','FDEN')
INSERT INTO ReglasSemanticas VALUES('PAR1 INTD','PRMT')
INSERT INTO ReglasSemanticas VALUES('PAR1 DBLD','PRMT')
INSERT INTO ReglasSemanticas VALUES('PAR1 STRD','PRMT')
INSERT INTO ReglasSemanticas VALUES('PAR1 CHRD','PRMT')
INSERT INTO ReglasSemanticas VALUES('PAR1 BOLD','PRMT')
INSERT INTO ReglasSemanticas VALUES('PRMT INTD','PRMT')
INSERT INTO ReglasSemanticas VALUES('PRMT DBLD','PRMT')
INSERT INTO ReglasSemanticas VALUES('PRMT CHRD','PRMT')
INSERT INTO ReglasSemanticas VALUES('PRMT STRD','PRMT')
INSERT INTO ReglasSemanticas VALUES('PRMT BOLD','PRMT')

/*return*/
INSERT INTO ReglasSemanticas VALUES('PR15 PAR1 INTE PAR2','S')
INSERT INTO ReglasSemanticas VALUES('PR15 PAR1 CHAR PAR2','S')
INSERT INTO ReglasSemanticas VALUES('PR15 PAR1 BOOL PAR2','S')
INSERT INTO ReglasSemanticas VALUES('PR15 PAR1 STRG PAR2','S')
INSERT INTO ReglasSemanticas VALUES('PR15 PAR1 DBLE PAR2','S')

/* for */
INSERT INTO ReglasSemanticas VALUES('PR06 PAR1 INTD OPA6 INTE', 'ASFR')
INSERT INTO ReglasSemanticas VALUES('ASFR PR19 BOOL STEP PAR2', 'S')
INSERT INTO ReglasSemanticas VALUES('ASFR PR19 BOOL STEP','FORI');
INSERT INTO ReglasSemanticas VALUES('PR06 PAR1 ASGE', 'ASFR')
INSERT INTO ReglasSemanticas VALUES('FORI INTE PAR2','S');
INSERT INTO ReglasSemanticas VALUES('PR17 ASGE','STEP');

/*do while*/
INSERT INTO ReglasSemanticas VALUES('PR04 PR20 PAR1 BOOL PAR2','S')


SELECT * FROM ReglasSemanticas
